= Accessing an FTP server using Skupper




Securely connect to an FTP server on a remote Kubernetes cluster

This example is part of a {examplesLink}[suite of examples] showing the different ways you can use Skupper to connect services across cloud providers, data centers, and edge sites.

.Overview

This example shows you how you can use Skupper to connect an FTP client on one Kubernetes cluster to an FTP server on another.

It demonstrates use of Skupper with multi-port services such as FTP.
It uses FTP in passive mode (which is more typical these days) and a https://github.com/skupperproject/skupper-example-ftp/blob/main/server/kubernetes.yaml#L25-L28[restricted port range] that simplifies Skupper configuration.

Prerequisites

* The `kubectl` command-line tool, version 1.15 or later (https://kubernetes.io/docs/tasks/tools/install-kubectl/[installation guide])
* Access to at least one Kubernetes cluster, from https://skupper.io/start/kubernetes.html[any provider you choose]

--
.Procedure
--

. Install the Skupper command-line tool
+
--

This example uses the Skupper command-line tool to deploy Skupper.
You need to install the `skupper` command only once for each development environment.

include::install.adoc[]

[,shell]
----
sudo dnf install skupper-cli
----






--

. Set up your namespaces
+
--

Skupper is designed for use with multiple Kubernetes namespaces, usually on different clusters.
The `skupper` and `kubectl` commands use your https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[kubeconfig] and current context to select the namespace where they operate.

Your kubeconfig is stored in a file in your home directory.
The `skupper` and `kubectl` commands use the `KUBECONFIG` environment variable to locate it.

A single kubeconfig supports only one active context per user.
Since you will be using multiple contexts at once in this exercise, you need to create distinct kubeconfigs.

For each namespace, open a new terminal window.
In each terminal, set the `KUBECONFIG` environment variable to a different path and log in to your cluster.
Then create the namespace you wish to use and set the namespace on your current context.

NOTE: The login procedure varies by provider.
See the documentation for yours:


* https://skupper.io/start/eks.html#cluster-access[Amazon Elastic Kubernetes Service (EKS)]
* https://skupper.io/start/aks.html#cluster-access[Azure Kubernetes Service (AKS)]
* https://skupper.io/start/gke.html#cluster-access[Google Kubernetes Engine (GKE)]
* https://skupper.io/start/ibmks.html#cluster-access[IBM Kubernetes Service]
* https://skupper.io/start/openshift.html#cluster-access[OpenShift]

*Public:*

[,shell]
----
export KUBECONFIG=~/.kube/config-public
# Enter your provider-specific login command
kubectl create namespace public
kubectl config set-context --current --namespace public
----

*Private:*

[,shell]
----
export KUBECONFIG=~/.kube/config-private
# Enter your provider-specific login command
kubectl create namespace private
kubectl config set-context --current --namespace private
----

--

. Deploy the FTP server
+
--

In Private, use `kubectl apply` to deploy the FTP server.

*Private:*

[,shell]
----
kubectl apply -f server
----

Sample output:

[,console]
----
$ kubectl apply -f server
deployment.apps/ftp-server created
----

--

. Create your sites
+
--

A Skupper site is a location where components of your application are running.
Sites are linked together to form a network for your application.
In Kubernetes, a site is associated with a namespace.

For each namespace, use `skupper init` to create a site.
This deploys the Skupper router and controller.
Then use `skupper status` to see the outcome.



*Public:*

[,shell]
----
skupper init
skupper status
----

Sample output:

[,console]
----
$ skupper init
Waiting for LoadBalancer IP or hostname...
Waiting for status...
Skupper is now installed in namespace 'public'.  Use 'skupper status' to get more information.

$ skupper status
Skupper is enabled for namespace "public". It is not connected to any other sites. It has no exposed services.
----

*Private:*

[,shell]
----
skupper init
skupper status
----

Sample output:

[,console]
----
$ skupper init
Waiting for LoadBalancer IP or hostname...
Waiting for status...
Skupper is now installed in namespace 'private'.  Use 'skupper status' to get more information.

$ skupper status
Skupper is enabled for namespace "private". It is not connected to any other sites. It has no exposed services.
----

As you move through the steps below, you can use `skupper status` at any time to check your progress.

--

. Link your sites
+
--

A Skupper link is a channel for communication between two sites.
Links serve as a transport for application connections and requests.

Creating a link requires use of two `skupper` commands in conjunction, `skupper token create` and `skupper link create`.

The `skupper token create` command generates a secret token that signifies permission to create a link.
The token also carries the link details.
Then, in a remote site, The `skupper link create` command uses the token to create a link to the site that generated it.

NOTE: The link token is truly a secret.
Anyone who has the token can link to your site.
Make sure that only those you trust have access to it.

First, use `skupper token create` in site Public to generate the token.
Then, use `skupper link create` in site Private to link the sites.

*Public:*

[,shell]
----
skupper token create ~/secret.token
----

Sample output:

[,console]
----
$ skupper token create ~/secret.token
Token written to ~/secret.token
----

*Private:*

[,shell]
----
skupper link create ~/secret.token
----

Sample output:

[,console]
----
$ skupper link create ~/secret.token
Site configured to link to https://10.105.193.154:8081/ed9c37f6-d78a-11ec-a8c7-04421a4c5042 (name=link1)
Check the status of the link using 'skupper link status'.
----

If your terminal sessions are on different machines, you may need to use `scp` or a similar tool to transfer the token securely.
By default, tokens expire after a single use or 15 minutes after creation.

--

. Expose the FTP server
+
--

In Private, use `skupper expose` to expose the FTP server on all linked sites.

*Private:*

[,shell]
----
skupper expose deployment/ftp-server --port 21100 --port 21
----

Sample output:

[,console]
----
$ skupper expose deployment/ftp-server --port 21100 --port 21
deployment ftp-server exposed as ftp-server
----

--

. Run the FTP client
+
--

In Public, use `kubectl run` and the `curl` image to perform FTP put and get operations.

*Public:*

[,shell]
----
echo "Hello!" | kubectl run ftp-client --stdin --rm --image=docker.io/curlimages/curl --restart=Never -- -s -T - ftp://example:example@ftp-server/greeting
kubectl run ftp-client --attach --rm --image=docker.io/curlimages/curl --restart=Never -- -s ftp://example:example@ftp-server/greeting
----

Sample output:

[,console]
----
$ echo "Hello!" | kubectl run ftp-client --stdin --rm --image=docker.io/curlimages/curl --restart=Never -- -s -T - ftp://example:example@ftp-server/greeting
pod "ftp-client" deleted

$ kubectl run ftp-client --attach --rm --image=docker.io/curlimages/curl --restart=Never -- -s ftp://example:example@ftp-server/greeting
Hello!
pod "ftp-client" deleted
----
