= Accessing ActiveMQ using Skupper




Use public cloud resources to process data from a private message broker

This example is part of a {examplesLink}[suite of examples] showing the different ways you can use Skupper to connect services across cloud providers, data centers, and edge sites.

.Overview

This example is a simple messaging application that shows how you can use Skupper to access an ActiveMQ broker at a remote site without exposing it to the public internet.

It contains two services:

* An ActiveMQ broker running in a private data center.
The broker has a queue named "notifications".
* An AMQP client running in the public cloud.
It sends 10 messages to "notifications" and then receives them back.

For the broker, this example uses the https://activemq.apache.org/components/artemis/[Apache ActiveMQ Artemis] image from https://artemiscloud.io/[ArtemisCloud.io].
The client is a simple https://quarkus.io/[Quarkus] application.

The example uses two Kubernetes namespaces, "private" and "public", to represent the private data center and public cloud.

Prerequisites

* The `kubectl` command-line tool, version 1.15 or later (https://kubernetes.io/docs/tasks/tools/install-kubectl/[installation guide])
* Access to at least one Kubernetes cluster, from https://skupper.io/start/kubernetes.html[any provider you choose]

--
.Procedure
--


* xref:skupper-example-activemq_READMEmd_item1[Install the Skupper command-line tool]

* xref:skupper-example-activemq_READMEmd_item2[Set up your namespaces]

* xref:skupper-example-activemq_READMEmd_item3[Deploy the message broker]

* xref:skupper-example-activemq_READMEmd_item4[Create your sites]

* xref:skupper-example-activemq_READMEmd_item5[Link your sites]

* xref:skupper-example-activemq_READMEmd_item6[Expose the message broker]

* xref:skupper-example-activemq_READMEmd_item7[Run the client]

. [[skupper-example-activemq_READMEmd_item1]]Install the Skupper command-line tool
+
--

This example uses the Skupper command-line tool to deploy Skupper.
You need to install the `skupper` command only once for each development environment.

See the SkupperInstallBookLink for details about installing the CLI. For configured systems, use the following command:

[,shell]
----
sudo dnf install skupper-cli
----






--

. [[skupper-example-activemq_READMEmd_item2]]Set up your namespaces
+
--

Skupper is designed for use with multiple Kubernetes namespaces, usually on different clusters.
The `skupper` and `kubectl` commands use your https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/[kubeconfig] and current context to select the namespace where they operate.

Your kubeconfig is stored in a file in your home directory.
The `skupper` and `kubectl` commands use the `KUBECONFIG` environment variable to locate it.

A single kubeconfig supports only one active context per user.
Since you will be using multiple contexts at once in this exercise, you need to create distinct kubeconfigs.

For each namespace, open a new terminal window.
In each terminal, set the `KUBECONFIG` environment variable to a different path and log in to your cluster.
Then create the namespace you wish to use and set the namespace on your current context.

NOTE: The login procedure varies by provider.
See the documentation for yours:


* https://skupper.io/start/eks.html#cluster-access[Amazon Elastic Kubernetes Service (EKS)]
* https://skupper.io/start/aks.html#cluster-access[Azure Kubernetes Service (AKS)]
* https://skupper.io/start/gke.html#cluster-access[Google Kubernetes Engine (GKE)]
* https://skupper.io/start/ibmks.html#cluster-access[IBM Kubernetes Service]
* https://skupper.io/start/openshift.html#cluster-access[OpenShift]

*Public:*

[,shell]
----
export KUBECONFIG=~/.kube/config-public
# Enter your provider-specific login command
kubectl create namespace public
kubectl config set-context --current --namespace public
----

*Private:*

[,shell]
----
export KUBECONFIG=~/.kube/config-private
# Enter your provider-specific login command
kubectl create namespace private
kubectl config set-context --current --namespace private
----

--

. [[skupper-example-activemq_READMEmd_item3]]Deploy the message broker
+
--

In Private, use the `kubectl apply` command to install the broker.

*Private:*

[,shell]
----
kubectl apply -f server
----

Sample output:

[,console]
----
$ kubectl apply -f server
deployment.apps/broker created
----

--

. [[skupper-example-activemq_READMEmd_item4]]Create your sites
+
--

A Skupper site is a location where components of your application are running.
Sites are linked together to form a network for your application.
In Kubernetes, a site is associated with a namespace.

For each namespace, use `skupper init` to create a site.
This deploys the Skupper router and controller.
Then use `skupper status` to see the outcome.



*Public:*

[,shell]
----
skupper init
skupper status
----

Sample output:

[,console]
----
$ skupper init
Waiting for LoadBalancer IP or hostname...
Waiting for status...
Skupper is now installed in namespace 'public'.  Use 'skupper status' to get more information.

$ skupper status
Skupper is enabled for namespace "public". It is not connected to any other sites. It has no exposed services.
----

*Private:*

[,shell]
----
skupper init
skupper status
----

Sample output:

[,console]
----
$ skupper init
Waiting for LoadBalancer IP or hostname...
Waiting for status...
Skupper is now installed in namespace 'private'.  Use 'skupper status' to get more information.

$ skupper status
Skupper is enabled for namespace "private". It is not connected to any other sites. It has no exposed services.
----

As you move through the steps below, you can use `skupper status` at any time to check your progress.

--

. [[skupper-example-activemq_READMEmd_item5]]Link your sites
+
--

A Skupper link is a channel for communication between two sites.
Links serve as a transport for application connections and requests.

Creating a link requires use of two `skupper` commands in conjunction, `skupper token create` and `skupper link create`.

The `skupper token create` command generates a secret token that signifies permission to create a link.
The token also carries the link details.
Then, in a remote site, The `skupper link create` command uses the token to create a link to the site that generated it.

NOTE: The link token is truly a secret.
Anyone who has the token can link to your site.
Make sure that only those you trust have access to it.

First, use `skupper token create` in site Public to generate the token.
Then, use `skupper link create` in site Private to link the sites.

*Public:*

[,shell]
----
skupper token create ~/secret.token
----

Sample output:

[,console]
----
$ skupper token create ~/secret.token
Token written to ~/secret.token
----

*Private:*

[,shell]
----
skupper link create ~/secret.token
----

Sample output:

[,console]
----
$ skupper link create ~/secret.token
Site configured to link to https://10.105.193.154:8081/ed9c37f6-d78a-11ec-a8c7-04421a4c5042 (name=link1)
Check the status of the link using 'skupper link status'.
----

If your terminal sessions are on different machines, you may need to use `scp` or a similar tool to transfer the token securely.
By default, tokens expire after a single use or 15 minutes after creation.

--

. [[skupper-example-activemq_READMEmd_item6]]Expose the message broker
+
--

In Private, use `skupper expose` to expose the broker on the Skupper network.

Then, in Public, use `kubectl get service/broker` to check that the service appears after a moment.

*Private:*

[,shell]
----
skupper expose deployment/broker --port 5672
----

Sample output:

[,console]
----
$ skupper expose deployment/broker --port 5672
deployment broker exposed as broker
----

*Public:*

[,shell]
----
kubectl get service/broker
----

Sample output:

[,console]
----
$ kubectl get service/broker
NAME     TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
broker   ClusterIP   10.100.58.95   <none>        5672/TCP   2s
----

--

. [[skupper-example-activemq_READMEmd_item7]]Run the client
+
--

In Public, use `kubectl run` to run the client.

*Public:*

[,shell]
----
kubectl run client --attach --rm --restart Never --image quay.io/skupper/activemq-example-client --env SERVER=broker
----

Sample output:

[,console]
----
$ kubectl run client --attach --rm --restart Never --image quay.io/skupper/activemq-example-client --env SERVER=broker
  ____  __  _____   ___  __ ____  ____
 --/ __ \/ / / / _ | / _ \/ //_/ / / / /
 -/ /_/ / /_/ / __ |/ , / ,< / // /\ \
--\___\_\____/_/ |_/_/|_/_/|_|\____/_/
2022-05-27 11:19:07,149 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16201: AMQP broker configured to broker:5672 for channel incoming-messages
2022-05-27 11:19:07,170 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16201: AMQP broker configured to broker:5672 for channel outgoing-messages
2022-05-27 11:19:07,198 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16212: Establishing connection with AMQP broker
2022-05-27 11:19:07,212 INFO  [io.sma.rea.mes.amqp] (main) SRMSG16212: Establishing connection with AMQP broker
2022-05-27 11:19:07,215 INFO  [io.quarkus] (main) client 1.0.0-SNAPSHOT on JVM (powered by Quarkus 2.9.2.Final) started in 0.397s.
2022-05-27 11:19:07,215 INFO  [io.quarkus] (main) Profile prod activated.
2022-05-27 11:19:07,215 INFO  [io.quarkus] (main) Installed features: [cdi, smallrye-context-propagation, smallrye-reactive-messaging, smallrye-reactive-messaging-amqp, vertx]
Sent message 1
Sent message 2
Sent message 3
Sent message 4
Sent message 5
Sent message 6
Sent message 7
Sent message 8
Sent message 9
Sent message 10
2022-05-27 11:19:07,434 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16213: Connection with AMQP broker established
2022-05-27 11:19:07,442 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16213: Connection with AMQP broker established
2022-05-27 11:19:07,468 INFO  [io.sma.rea.mes.amqp] (vert.x-eventloop-thread-0) SRMSG16203: AMQP Receiver listening address notifications
Received message 1
Received message 2
Received message 3
Received message 4
Received message 5
Received message 6
Received message 7
Received message 8
Received message 9
Received message 10
Result: OK
----
