== skupper completion

== skupper debug dump

== skupper debug events

== skupper debug

== skupper debug policies

== skupper debug service

== skupper delete

== skupper expose

--address::
+
--
The Skupper address to expose
--

--aggregate::
+
--
The aggregation strategy to use. One of 'json' or 'multipart'. If specified requests to this service will be sent to all registered implementations and the responses aggregated.
--

--bridge-image::
+
--
The image to use for a bridge running external to the skupper router
--

--enable-ingress-from-target-site::
+
--
Determines whether access to the Skupper service is enabled in the site the target was exposed through. Always (default) or Never are valid values.
--

--event-channel::
+
--
specified, this service will be a channel for multicast events.
--

--generate-tls-secrets::
+
--
specified, the service will be exposed over TLS
--

--headless::
+
--
through a headless service (valid only for a statefulset target)
--

--port::
+
--
The ports to expose on
--

--protocol::
+
--
The protocol to proxy (tcp, http, or http2) (default "tcp")
--

--proxy-cpu::
+
--
CPU request for router pods
--

--proxy-cpu-limit::
+
--
CPU limit for router pods
--

--proxy-memory::
+
--
Memory request for router pods
--

--proxy-memory-limit::
+
--
Memory limit for router pods
--

--proxy-node-selector::
+
--
Node selector to control placement of router pods
--

--proxy-pod-affinity::
+
--
Pod affinity label matches to control placement of router pods
--

--proxy-pod-antiaffinity::
+
--
Pod antiaffinity label matches to control placement of router pods
--

--publish-not-ready-addresses::
+
--
specified, skupper will not wait for pods to be ready
--

--target-namespace::
+
--
Expose resources from a specific namespace
--

--target-port::
+
--
The ports to target on pods
--

--tls-cert::
+
--
K8s secret name with custom certificates to expose the service over TLS
--

--tls-trust::
+
--
K8s secret name with the CA to expose the service over TLS
--

== skupper gateway bind

--aggregate::
+
--
The aggregation strategy to use. One of 'json' or 'multipart'. If specified requests to this service will be sent to all registered implementations and the responses aggregated.
--

--event-channel::
+
--
specified, this service will be a channel for multicast events.
--

== skupper gateway delete

== skupper gateway export-config

== skupper gateway expose

--aggregate::
+
--
The aggregation strategy to use. One of 'json' or 'multipart'. If specified requests to this service will be sent to all registered implementations and the responses aggregated.
--

--event-channel::
+
--
specified, this service will be a channel for multicast events.
--

--protocol::
+
--
The protocol to gateway (tcp, http or http2). (default "tcp")
--

--type::
+
--
The gateway type one of: 'service', 'docker', 'podman' (default "service")
--

== skupper gateway forward

--aggregate::
+
--
The aggregation strategy to use. One of 'json' or 'multipart'. If specified requests to this service will be sent to all registered implementations and the responses aggregated.
--

--event-channel::
+
--
specified, this service will be a channel for multicast events.
--

--loopback::
+
--
from loopback only
--

== skupper gateway generate-bundle

== skupper gateway init

--config::
+
--
The gateway config file to use for initialization
--

--type::
+
--
The gateway type one of: 'service', 'docker', 'podman' (default "service")
--

== skupper gateway

== skupper gateway status

== skupper gateway unbind

== skupper gateway unexpose

--delete-last::
+
--
the gateway if no services remain (default true)
--

== skupper gateway unforward

== skupper init

--site-name::
+
--
Provide a specific name for this skupper installation
--

--ingress::
+
--
Setup Skupper ingress to one of: [route|loadbalancer|nodeport|nginx-ingress-v1|contour-http-proxy|ingress|none]. If not specified route is used when available, otherwise loadbalancer is used.

Options include:

* route
* loadbalancer
* nodeport
* nginx-ingress-v1
* contour-http-proxy
* ingress
* none
--

--router-mode::
+
--
Skupper router-mode (default "interior")
--

--labels::
+
--
Labels to add to resources created by skupper
--

--router-logging::
+
--
Logging settings for router. 'trace', 'debug', 'info' (default), 'notice', 'warning', and 'error' are valid values.
--

--enable-console::
+
--
skupper console must be used in conjunction with '--enable-flow-collector' flag
--

--ingress-host::
+
--
Hostname or alias by which the ingress route or proxy can be reached
--

--create-network-policy::
+
--
network policy to restrict access to skupper services exposed through this site to current pods in namespace
--

--console-auth::
+
--
Authentication mode for console(s). One of: 'openshift', 'internal', 'unsecured' (default "internal")
--

--console-user::
+
--
Skupper console user. Valid only when --console-auth=internal
--

--console-password::
+
--
Skupper console user. Valid only when --console-auth=internal
--

--console-ingress::
+
--
Determines if/how console is exposed outside cluster. If not specified uses value of --ingress. One of: [route|loadbalancer|nodeport|nginx-ingress-v1|contour-http-proxy|ingress|none].

Options include:

* route
* loadbalancer
* nodeport
* nginx-ingress-v1
* contour-http-proxy
* ingress
* none
--

--enable-rest-api::
+
--
REST API
--

--ingress-annotations::
+
--
Annotations to add to skupper ingress
--

--annotations::
+
--
Annotations to add to skupper pods
--

--router-service-annotations::
+
--
Annotations to add to skupper router service
--

--router-pod-annotations::
+
--
Annotations to add to skupper router pod
--

--controller-service-annotation::
+
--
Annotations to add to skupper controller service
--

--controller-pod-annotation::
+
--
Annotations to add to skupper controller pod
--

--prometheus-server-pod-annotation::
+
--
Annotations to add to skupper prometheus pod
--

--enable-service-sync::
+
--
in cross-site service synchronization (default true)
--

--service-sync-site-ttl::
+
--
Time after which stale services, i.e. those whose site has not been heard from, created through service-sync are removed.
--

--enable-flow-collector::
+
--
cross-site flow collection for the application network
--

--routers::
+
--
Number of router replicas to start
--

--router-cpu::
+
--
CPU request for router pods
--

--router-memory::
+
--
Memory request for router pods
--

--router-cpu-limit::
+
--
CPU limit for router pods
--

--router-memory-limit::
+
--
Memory limit for router pods
--

--router-node-selector::
+
--
Node selector to control placement of router pods
--

--router-pod-affinity::
+
--
Pod affinity label matches to control placement of router pods
--

--router-pod-antiaffinity::
+
--
Pod antiaffinity label matches to control placement of router pods
--

--router-ingress-host::
+
--
Host through which node is accessible when using nodeport as ingress.
--

--router-load-balancer-ip::
+
--
Load balancer ip that will be used for router service, if supported by cloud provider
--

--router-data-connection-count::
+
--
Configures the number of data connections the router will use when linking to other routers
--

--controller-cpu::
+
--
CPU request for controller pods
--

--controller-memory::
+
--
Memory request for controller pods
--

--controller-cpu-limit::
+
--
CPU limit for controller pods
--

--controller-memory-limit::
+
--
Memory limit for controller pods
--

--controller-node-selector::
+
--
Node selector to control placement of controller pods
--

--controller-pod-affinity::
+
--
Pod affinity label matches to control placement of controller pods
--

--controller-pod-antiaffinity::
+
--
Pod antiaffinity label matches to control placement of controller pods
--

--controller-ingress-host::
+
--
Host through which node is accessible when using nodeport as ingress.
--

--controller-load-balancer-ip::
+
--
Load balancer ip that will be used for controller service, if supported by cloud provider
--

--config-sync-cpu::
+
--
CPU request for config-sync pods
--

--config-sync-memory::
+
--
Memory request for config-sync pods
--

--config-sync-cpu-limit::
+
--
CPU limit for config-sync pods
--

--config-sync-memory-limit::
+
--
Memory limit for config-sync pods
--

--enable-cluster-permissions::
+
--
cluster wide permissions in order to expose deployments/statefulsets in other namespaces
--

--flow-collector-record-ttl::
+
--
Time after which terminated flow records are deleted, i.e. those flow records that have an end time set. Default is 15 minutes.
--

--flow-collector-cpu::
+
--
CPU request for flow collector pods
--

--flow-collector-memory::
+
--
Memory request for flow collector pods
--

--flow-collector-cpu-limit::
+
--
CPU limit for flow collector pods
--

--flow-collector-memory-limit::
+
--
Memory limit for flow collector pods
--

--prometheus-cpu::
+
--
CPU request for prometheus pods
--

--prometheus-memory::
+
--
Memory request for prometheus pods
--

--prometheus-cpu-limit::
+
--
CPU limit for prometheus pods
--

--prometheus-memory-limit::
+
--
Memory limit for prometheus pods
--

--timeout::
+
--
Configurable timeout for the ingress loadbalancer option. (default 2m0s)
--

--enable-skupper-events::
+
--
sending Skupper events to Kubernetes (default true)
--

== skupper link create

--cost::
+
--
Specify a cost for this link. (default 1)
--

--name::
+
--
Provide a specific name for the link (used when deleting it)
--

== skupper link delete

== skupper link

== skupper link status

--wait::
+
--
The number of seconds to wait for links to become connected
--

== skupper

== skupper network

== skupper network status

== skupper revoke-access

== skupper service bind

--headless::
+
--
through a headless service (valid only for a statefulset target)
--

--proxy-cpu::
+
--
CPU request for router pods
--

--proxy-cpu-limit::
+
--
CPU limit for router pods
--

--proxy-memory::
+
--
Memory request for router pods
--

--proxy-memory-limit::
+
--
Memory limit for router pods
--

--proxy-node-selector::
+
--
Node selector to control placement of router pods
--

--proxy-pod-affinity::
+
--
Pod affinity label matches to control placement of router pods
--

--proxy-pod-antiaffinity::
+
--
Pod antiaffinity label matches to control placement of router pods
--

--publish-not-ready-addresses::
+
--
specified, skupper will not wait for pods to be ready
--

--target-namespace::
+
--
Expose resources from a specific namespace
--

--target-port::
+
--
The port the target is listening on (you can also use colon to map source-port to a target-port).
--

--tls-trust::
+
--
K8s secret name with the CA to expose the service over TLS
--

== skupper service create

--aggregate::
+
--
The aggregation strategy to use. One of 'json' or 'multipart'. If specified requests to this service will be sent to all registered implementations and the responses aggregated.
--

--bridge-image::
+
--
The image to use for a bridge running external to the skupper router
--

--enable-ingress::
+
--
Determines whether access to the Skupper service is enabled in this site. Valid values are Always (default) or Never.
--

--event-channel::
+
--
specified, this service will be a channel for multicast events.
--

--generate-tls-secrets::
+
--
specified, the service communication will be encrypted using TLS
--

--protocol::
+
--
The mapping in use for this service address (tcp, http, http2) (default "tcp")
--

--tls-cert::
+
--
K8s secret name with custom certificates to encrypt the communication using TLS
--

== skupper service delete

== skupper service label

== skupper service

== skupper service status

--show-labels::
+
--
service labels
--

== skupper service unbind

--target-namespace::
+
--
Target namespace for exposed resource
--

== skupper status

== skupper token create

--expiry::
+
--
Expiration time for claim (only valid if --token-type=claim) (default 15m0s)
--

--name::
+
--
Provide a specific identity as which connecting skupper installation will be authenticated (default "skupper")
--

--uses::
+
--
Number of uses for which claim will be valid (only valid if --token-type=claim) (default 1)
--

== skupper token

== skupper unexpose

--address::
+
--
Skupper address the target was exposed as
--

--target-namespace::
+
--
Target namespace for exposed resource
--

== skupper update

--force-restart::
+
--
skupper daemons even if image tag is not updated
--

== skupper version manifest

== skupper version

